FROM docker.oa.isuwang.com:5000/system/tomcat7-jdk8:7.0.90
VOLUME /tmp
ADD isuwang-security-app-1.0-SNAPSHOT.jar app.jar
RUN bash -c 'touch /app.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS  -Djava.security.egd=file:/dev/./urandom -jar -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} /app.jar" ]